#!/system/SystemTweakerFREE/ash

busybox=/system/SystemTweakerFREE/busybox

sync
$busybox sysctl -w vm.drop_caches=3
$busybox sysctl -w vm.dirty_ratio=10
$busybox sysctl -w vm.dirty_background_ratio=0


