#!/data/data/com.nowenui.systemtweakerfree/files/ash

busybox=/data/data/com.nowenui.systemtweakerfree/files/busybox

sync
$busybox sysctl -w vm.drop_caches=3
$busybox sysctl -w vm.dirty_ratio=1
$busybox sysctl -w vm.dirty_background_ratio=1


