#!/data/data/com.nowenui.systemtweakerfree/files/ash

busybox=/data/data/com.nowenui.systemtweakerfree/files/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
$busybox echo "48" > /sys/module/lowmemorykiller/parameters/cost
fi

# Debug level
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
$busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
fi

# Minfree Values 
mem=`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`

#512 and less
oom11=8
oom21=12
oom31=28
oom41=32
oom51=36
oom61=42

lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));

#768
oom12=8
oom22=18
oom32=21
oom42=41
oom52=54
oom62=70

lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));

#1024
oom13=8
oom23=12
oom33=35
oom43=42
oom53=56
oom63=72

lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));

#1536
oom14=8
oom24=12
oom34=38
oom44=46
oom54=70
oom64=82

lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));

#2048
oom15=8
oom25=12
oom35=45
oom45=56
oom55=72
oom65=97

lmk15=$(($oom15*1024/4));
lmk25=$(($oom25*1024/4));
lmk35=$(($oom35*1024/4));
lmk45=$(($oom45*1024/4));
lmk55=$(($oom55*1024/4));
lmk65=$(($oom65*1024/4));

#3072
oom16=8
oom26=12
oom36=48
oom46=72
oom56=90
oom66=128

lmk16=$(($oom16*1024/4));
lmk26=$(($oom26*1024/4));
lmk36=$(($oom36*1024/4));
lmk46=$(($oom46*1024/4));
lmk56=$(($oom56*1024/4));
lmk66=$(($oom66*1024/4));

#3072+
oom17=8
oom27=12
oom37=52
oom47=68
oom57=82
oom67=128

lmk17=$(($oom17*1024/4));
lmk27=$(($oom27*1024/4));
lmk37=$(($oom37*1024/4));
lmk47=$(($oom47*1024/4));
lmk57=$(($oom57*1024/4));
lmk67=$(($oom67*1024/4));

if [ "$mem" -lt 524288 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 786432 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1048576 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1572864 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 2097152 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk15,$lmk25,$lmk35,$lmk45,$lmk55,$lmk65" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 3145728 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk16,$lmk26,$lmk36,$lmk46,$lmk56,$lmk66" > /sys/module/lowmemorykiller/parameters/minfree
else 
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk17,$lmk27,$lmk37,$lmk47,$lmk57,$lmk67" > /sys/module/lowmemorykiller/parameters/minfree
fi
